language: node_js

before_install:
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

install:
  - npm install
  - npm install coveralls

script:
  - npm run coverage
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js

node_js:
  - 'stable'
  - '5'
  - '4'
